// next-env.d.ts is generated by `next build` / `next dev` and gitignored, so a
// fresh checkout that type-checks BEFORE building (CI runs `tsc --noEmit`
// first) has no declarations for static image imports — the car tiles and
// heroes in app/lib/carImageAssets.ts import their files directly. This loads
// the same declarations next-env.d.ts would.
/// <reference types="next/image-types/global" />
