import { describe, it, expect } from "vitest";
import { LIVE_BOARDS, liveBoardFor, hasLiveBoard } from "../app/data/liveBoards";
import { liveCharts as burnaLive } from "../app/data/liveCharts";
import { artistBySlug, afrobeatsSlugs } from "../app/data/afrobeats";
import sitemap from "../app/sitemap";
import { searchIndex } from "../app/lib/searchIndex";

// The board's live charts are generated by the same pipeline as Burna Boy's
// (scripts/build-live-charts.mjs --artist=<slug>) into a file of their own.
// These are the invariants a regenerated snapshot must keep — the data itself
// changes every hour, so nothing here pins a figure.
describe("the board's live charts", () => {
  it("belongs to an artist who is actually on the board", () => {
    for (const b of LIVE_BOARDS) expect(artistBySlug(b.slug), b.slug).toBeTruthy();
  });

  it("is never empty, and never Burna Boy's data", () => {
    for (const b of LIVE_BOARDS) {
      expect(b.releases.length, b.slug).toBeGreaterThan(5);
      expect(b.placements, b.slug).toBeGreaterThan(25);
      // The bug this guards: one shared module-level fetch cache used to mean
      // a second artist's page could render Burna Boy's snapshot.
      const shared = b.releases.filter((r) => burnaLive.some((x) => x.title === r.title));
      expect(shared.length, `${b.slug} shares ${shared.length} titles with Burna Boy`).toBeLessThan(
        b.releases.length / 2
      );
    }
  });

  it("counts its own totals from its own rows", () => {
    for (const b of LIVE_BOARDS) {
      const entries = b.releases.flatMap((r) => r.platforms.flatMap((p) => p.entries));
      expect(b.placements, b.slug).toBe(entries.length);
      expect(b.countries, b.slug).toBe(new Set(entries.map((e) => e.country)).size);
      expect(b.platformTotals.reduce((n, p) => n + p.placements, 0), b.slug).toBe(entries.length);
    }
  });

  it("never lists the same country twice inside one platform", () => {
    for (const b of LIVE_BOARDS)
      for (const r of b.releases)
        for (const p of r.platforms) {
          const codes = p.entries.map((e) => e.country);
          expect(new Set(codes).size, `${b.slug} → ${r.title} → ${p.platform}`).toBe(codes.length);
        }
  });

  // "Kese" and "Kese (Dance)", "Wa" and "Wa (Live)", "Ako" and "Ako - Live in
  // London": one record under two names, the same chart row counted twice,
  // until scripts/live-artists.mjs learned the alias. Titles alone are a weak
  // test — this checks the thing that is actually wrong, two releases holding
  // the SAME position on the SAME chart. Song and album charts are separate
  // charts, so a song and an album may share a position legitimately.
  it("never counts one chart row under two titles", () => {
    for (const b of LIVE_BOARDS) {
      const seen = new Map<string, Set<string>>();
      for (const r of b.releases)
        for (const p of r.platforms)
          for (const e of p.entries) {
            const key = `${r.kind}|${p.platform}|${e.country}|${e.position}`;
            if (!seen.has(key)) seen.set(key, new Set());
            seen.get(key)!.add(r.title);
          }
      const clashes = [...seen.entries()]
        .filter(([, titles]) => titles.size > 1)
        .map(([key, titles]) => `${key}: ${[...titles].join(" / ")}`);
      expect(clashes, b.slug).toEqual([]);
    }
  });

  it("resolves artwork for most releases", () => {
    for (const b of LIVE_BOARDS) {
      const withArt = b.releases.filter((r) => r.cover);
      expect(withArt.length / b.releases.length, `${b.slug} artwork coverage`).toBeGreaterThan(0.8);
      for (const r of withArt) expect(r.cover, `${b.slug} → ${r.title}`).toMatch(/^https:\/\//);
    }
  });

  it("points its country panels at its own endpoint", () => {
    for (const b of LIVE_BOARDS) expect(b.api).toBe(`/api/v1/live-charts/${b.slug}`);
  });

  it("is in the sitemap and the search index", async () => {
    const routes = (await sitemap()).map((e) => e.url);
    const paths = new Set(searchIndex.map((d) => d.path));
    for (const b of LIVE_BOARDS) {
      expect(routes.some((u) => u.endsWith(`/afrobeats/${b.slug}/live`)), b.slug).toBe(true);
      expect(paths.has(`/afrobeats/${b.slug}/live`), b.slug).toBe(true);
    }
  });

  it("covers every artist on the board, and nobody else", () => {
    // A live board needs no register sweep — the platform charts are readable
    // today — so the pending three have one as well.
    expect(LIVE_BOARDS.map((b) => b.slug).sort()).toEqual(afrobeatsSlugs.slice().sort());
    expect(hasLiveBoard("wizkid")).toBe(true);
    expect(hasLiveBoard("seyi-vibez")).toBe(true);
    // Burna Boy's live charts are the site's own page, not a board entry.
    expect(hasLiveBoard("burna-boy")).toBe(false);
    expect(liveBoardFor("nobody")).toBeUndefined();
  });
});
