import { describe, it, expect } from "vitest";
import { LIVE_BOARDS, liveBoardFor, hasLiveBoard } from "../app/data/liveBoards";
import { liveCharts as burnaLive } from "../app/data/liveCharts";
import { artistBySlug } from "../app/data/afrobeats";
import sitemap from "../app/sitemap";
import { searchIndex } from "../app/lib/searchIndex";

// The board's live charts are generated by the same pipeline as Burna Boy's
// (scripts/build-live-charts.mjs --artist=<slug>) into a file of their own.
// These are the invariants a regenerated snapshot must keep — the data itself
// changes every hour, so nothing here pins a figure.
describe("the board's live charts", () => {
  it("belongs to an artist who is actually on the board", () => {
    for (const b of LIVE_BOARDS) expect(artistBySlug(b.slug), b.slug).toBeTruthy();
  });

  it("is never empty, and never Burna Boy's data", () => {
    for (const b of LIVE_BOARDS) {
      expect(b.releases.length, b.slug).toBeGreaterThan(5);
      expect(b.placements, b.slug).toBeGreaterThan(25);
      // The bug this guards: one shared module-level fetch cache used to mean
      // a second artist's page could render Burna Boy's snapshot.
      const shared = b.releases.filter((r) => burnaLive.some((x) => x.title === r.title));
      expect(shared.length, `${b.slug} shares ${shared.length} titles with Burna Boy`).toBeLessThan(
        b.releases.length / 2
      );
    }
  });

  it("counts its own totals from its own rows", () => {
    for (const b of LIVE_BOARDS) {
      const entries = b.releases.flatMap((r) => r.platforms.flatMap((p) => p.entries));
      expect(b.placements, b.slug).toBe(entries.length);
      expect(b.countries, b.slug).toBe(new Set(entries.map((e) => e.country)).size);
      expect(b.platformTotals.reduce((n, p) => n + p.placements, 0), b.slug).toBe(entries.length);
    }
  });

  it("never lists the same country twice inside one platform", () => {
    for (const b of LIVE_BOARDS)
      for (const r of b.releases)
        for (const p of r.platforms) {
          const codes = p.entries.map((e) => e.country);
          expect(new Set(codes).size, `${b.slug} → ${r.title} → ${p.platform}`).toBe(codes.length);
        }
  });

  // "Kese" and "Kese (Dance)" are one record under two names, and shipped as
  // two rows both at Nigeria #57 until scripts/live-artists.mjs learned the
  // alias. Two rows whose titles differ only by a parenthetical are the shape
  // of that bug.
  it("does not carry the same record under two names", () => {
    for (const b of LIVE_BOARDS) {
      const bare = (t: string) => t.replace(/\s*\([^)]*\)\s*$/, "").toLowerCase().trim();
      const songs = b.releases.filter((r) => r.kind === "song").map((r) => r.title);
      const dupes = songs.filter(
        (t, i) => songs.some((o, j) => i !== j && bare(o) === bare(t) && o !== t)
      );
      expect(dupes, b.slug).toEqual([]);
    }
  });

  it("resolves artwork for most releases", () => {
    for (const b of LIVE_BOARDS) {
      const withArt = b.releases.filter((r) => r.cover);
      expect(withArt.length / b.releases.length, `${b.slug} artwork coverage`).toBeGreaterThan(0.8);
      for (const r of withArt) expect(r.cover, `${b.slug} → ${r.title}`).toMatch(/^https:\/\//);
    }
  });

  it("points its country panels at its own endpoint", () => {
    for (const b of LIVE_BOARDS) expect(b.api).toBe(`/api/v1/live-charts/${b.slug}`);
  });

  it("is in the sitemap and the search index", async () => {
    const routes = (await sitemap()).map((e) => e.url);
    const paths = new Set(searchIndex.map((d) => d.path));
    for (const b of LIVE_BOARDS) {
      expect(routes.some((u) => u.endsWith(`/afrobeats/${b.slug}/live`)), b.slug).toBe(true);
      expect(paths.has(`/afrobeats/${b.slug}/live`), b.slug).toBe(true);
    }
  });

  it("knows who has a live board and who does not", () => {
    expect(hasLiveBoard("wizkid")).toBe(true);
    expect(hasLiveBoard("tems")).toBe(false);
    expect(liveBoardFor("nobody")).toBeUndefined();
  });
});
