// Which Afrobeats Board artists have a live-charts board, and where their data
// lives.
//
// Burna Boy is NOT here. His live charts are the site's own subject: they sit
// at /live-charts, carry his run history and trend charts, and are wired
// through app/data/liveCharts.ts directly. This registry is the board's
// artists, all generated by the same pipeline in one pass
// (scripts/build-live-charts.mjs --artist=a,b,c) into a file each.
//
// Adding an artist is three steps: add them to scripts/live-artists.mjs, run
// the builder, and add a row here. The route, the API endpoint, the OG card
// and the button on their artist page all follow from this.

import { countriesOf } from "../lib/liveChartMeta";
import { liveCharts as wizkid, liveChartsUpdated as wizkidAt, liveChartsBuiltAt as wizkidBuilt, type LiveRelease } from "./liveCharts.wizkid";
import { liveCharts as davido, liveChartsUpdated as davidoAt, liveChartsBuiltAt as davidoBuilt } from "./liveCharts.davido";
import { liveCharts as rema, liveChartsUpdated as remaAt, liveChartsBuiltAt as remaBuilt } from "./liveCharts.rema";
import { liveCharts as tems, liveChartsUpdated as temsAt, liveChartsBuiltAt as temsBuilt } from "./liveCharts.tems";
import { liveCharts as tyla, liveChartsUpdated as tylaAt, liveChartsBuiltAt as tylaBuilt } from "./liveCharts.tyla";
import { liveCharts as ayra, liveChartsUpdated as ayraAt, liveChartsBuiltAt as ayraBuilt } from "./liveCharts.ayra-starr";
import { liveCharts as asake, liveChartsUpdated as asakeAt, liveChartsBuiltAt as asakeBuilt } from "./liveCharts.asake";
import { liveCharts as omahLay, liveChartsUpdated as omahLayAt, liveChartsBuiltAt as omahLayBuilt } from "./liveCharts.omah-lay";
import { liveCharts as seyiVibez, liveChartsUpdated as seyiVibezAt, liveChartsBuiltAt as seyiVibezBuilt } from "./liveCharts.seyi-vibez";
import { liveCharts as victony, liveChartsUpdated as victonyAt, liveChartsBuiltAt as victonyBuilt } from "./liveCharts.victony";
import { liveCharts as fireboyDml, liveChartsUpdated as fireboyDmlAt, liveChartsBuiltAt as fireboyDmlBuilt } from "./liveCharts.fireboy-dml";
import { liveCharts as ckay, liveChartsUpdated as ckayAt, liveChartsBuiltAt as ckayBuilt } from "./liveCharts.ckay";
import { liveCharts as olamide, liveChartsUpdated as olamideAt, liveChartsBuiltAt as olamideBuilt } from "./liveCharts.olamide";
import { liveCharts as blackSherif, liveChartsUpdated as blackSherifAt, liveChartsBuiltAt as blackSherifBuilt } from "./liveCharts.black-sherif";
import { liveCharts as bnxn, liveChartsUpdated as bnxnAt, liveChartsBuiltAt as bnxnBuilt } from "./liveCharts.bnxn";
import { liveCharts as kizzDaniel, liveChartsUpdated as kizzDanielAt, liveChartsBuiltAt as kizzDanielBuilt } from "./liveCharts.kizz-daniel";
import { liveCharts as ruger, liveChartsUpdated as rugerAt, liveChartsBuiltAt as rugerBuilt } from "./liveCharts.ruger";
import { liveCharts as oxlade, liveChartsUpdated as oxladeAt, liveChartsBuiltAt as oxladeBuilt } from "./liveCharts.oxlade";
import { liveCharts as tiwaSavage, liveChartsUpdated as tiwaSavageAt, liveChartsBuiltAt as tiwaSavageBuilt } from "./liveCharts.tiwa-savage";

export interface LiveBoard {
  slug: string;
  releases: LiveRelease[];
  updated: string;
  /** The minute the snapshot was rebuilt — the API's `builtAt`. */
  builtAt: string;
  /** Where the page's country panels fetch the full snapshot from. */
  api: string;
  placements: number;
  countries: number;
  numberOnes: number;
  platformTotals: { platform: string; placements: number; numberOnes: number }[];
}

/** Totals derived from the rows, so they can never disagree with what renders. */
function board(slug: string, releases: LiveRelease[], updated: string, builtAt: string): LiveBoard {
  const entries = releases.flatMap((r) => r.platforms.flatMap((p) => p.entries));
  const platforms = [...new Set(releases.flatMap((r) => r.platforms.map((p) => p.platform)))];
  return {
    slug,
    releases,
    updated,
    builtAt,
    api: `/api/v1/live-charts/${slug}`,
    placements: entries.length,
    countries: countriesOf(entries),
    numberOnes: releases.reduce((n, r) => n + r.platforms.reduce((m, p) => m + p.numberOnes, 0), 0),
    platformTotals: platforms
      .map((platform) => {
        const blocks = releases.flatMap((r) => r.platforms.filter((p) => p.platform === platform));
        return {
          platform,
          placements: blocks.reduce((n, p) => n + p.entries.length, 0),
          numberOnes: blocks.reduce((n, p) => n + p.numberOnes, 0),
        };
      })
      .sort((a, b) => b.placements - a.placements),
  };
}

// In the order each artist joined the board, and within a batch most-certified
// first. Nothing depends on the order: the hub sorts its own tiles, and the API
// and the sitemap only list the slugs. A live board needs no register sweep —
// the platform charts are readable today — but a row here needs an
// afrobeats.ts entry, and every artist on the board has a row.
export const LIVE_BOARDS: LiveBoard[] = [
  board("wizkid", wizkid, wizkidAt, wizkidBuilt),
  board("davido", davido, davidoAt, davidoBuilt),
  board("rema", rema, remaAt, remaBuilt),
  board("tems", tems, temsAt, temsBuilt),
  board("tyla", tyla, tylaAt, tylaBuilt),
  board("ayra-starr", ayra, ayraAt, ayraBuilt),
  board("asake", asake, asakeAt, asakeBuilt),
  board("omah-lay", omahLay, omahLayAt, omahLayBuilt),
  board("seyi-vibez", seyiVibez, seyiVibezAt, seyiVibezBuilt),
  board("victony", victony, victonyAt, victonyBuilt),
  board("fireboy-dml", fireboyDml, fireboyDmlAt, fireboyDmlBuilt),
  board("ckay", ckay, ckayAt, ckayBuilt),
  board("olamide", olamide, olamideAt, olamideBuilt),
  board("black-sherif", blackSherif, blackSherifAt, blackSherifBuilt),
  board("bnxn", bnxn, bnxnAt, bnxnBuilt),
  board("kizz-daniel", kizzDaniel, kizzDanielAt, kizzDanielBuilt),
  board("ruger", ruger, rugerAt, rugerBuilt),
  board("oxlade", oxlade, oxladeAt, oxladeBuilt),
  board("tiwa-savage", tiwaSavage, tiwaSavageAt, tiwaSavageBuilt),
];

export const liveBoardFor = (slug: string) => LIVE_BOARDS.find((b) => b.slug === slug);
export const hasLiveBoard = (slug: string) => LIVE_BOARDS.some((b) => b.slug === slug);
