// Which Afrobeats Board artists have a live-charts board, and where their data
// lives.
//
// Burna Boy is NOT here. His live charts are the site's own subject: they sit
// at /live-charts, carry his run history and trend charts, and are wired
// through app/data/liveCharts.ts directly. This registry is the board's
// artists, each generated by the same pipeline
// (scripts/build-live-charts.mjs --artist=<slug>) into its own file.
//
// Adding an artist is three steps: add them to scripts/live-artists.mjs, run
// the builder, and add a row here. The route, the API endpoint and the button
// on their artist page all follow from this.

import {
  liveCharts as wizkidCharts,
  liveChartsUpdated as wizkidUpdated,
  type LiveRelease,
} from "./liveCharts.wizkid";

export interface LiveBoard {
  slug: string;
  releases: LiveRelease[];
  updated: string;
  /** Where the page's country panels fetch the full snapshot from. */
  api: string;
  placements: number;
  countries: number;
  numberOnes: number;
  platformTotals: { platform: string; placements: number; numberOnes: number }[];
}

/** Totals derived from the rows, so they can never disagree with what renders. */
function board(slug: string, releases: LiveRelease[], updated: string, api: string): LiveBoard {
  const entries = releases.flatMap((r) => r.platforms.flatMap((p) => p.entries));
  const platforms = [...new Set(releases.flatMap((r) => r.platforms.map((p) => p.platform)))];
  return {
    slug,
    releases,
    updated,
    api,
    placements: entries.length,
    countries: new Set(entries.map((e) => e.country)).size,
    numberOnes: releases.reduce((n, r) => n + r.platforms.reduce((m, p) => m + p.numberOnes, 0), 0),
    platformTotals: platforms
      .map((platform) => {
        const blocks = releases.flatMap((r) => r.platforms.filter((p) => p.platform === platform));
        return {
          platform,
          placements: blocks.reduce((n, p) => n + p.entries.length, 0),
          numberOnes: blocks.reduce((n, p) => n + p.numberOnes, 0),
        };
      })
      .sort((a, b) => b.placements - a.placements),
  };
}

export const LIVE_BOARDS: LiveBoard[] = [
  board("wizkid", wizkidCharts, wizkidUpdated, "/api/v1/live-charts/wizkid"),
];

export const liveBoardFor = (slug: string) => LIVE_BOARDS.find((b) => b.slug === slug);
export const hasLiveBoard = (slug: string) => LIVE_BOARDS.some((b) => b.slug === slug);
