// Which Afrobeats Board artists have a live-charts board, and where their data
// lives.
//
// Burna Boy is NOT here. His live charts are the site's own subject: they sit
// at /live-charts, carry his run history and trend charts, and are wired
// through app/data/liveCharts.ts directly. This registry is the board's
// artists, all generated by the same pipeline in one pass
// (scripts/build-live-charts.mjs --artist=a,b,c) into a file each.
//
// Adding an artist is three steps: add them to scripts/live-artists.mjs, run
// the builder, and add a row here. The route, the API endpoint, the OG card
// and the button on their artist page all follow from this.

import { countriesOf } from "../lib/liveChartMeta";
import { liveCharts as wizkid, liveChartsUpdated as wizkidAt, type LiveRelease } from "./liveCharts.wizkid";
import { liveCharts as davido, liveChartsUpdated as davidoAt } from "./liveCharts.davido";
import { liveCharts as rema, liveChartsUpdated as remaAt } from "./liveCharts.rema";
import { liveCharts as tems, liveChartsUpdated as temsAt } from "./liveCharts.tems";
import { liveCharts as tyla, liveChartsUpdated as tylaAt } from "./liveCharts.tyla";
import { liveCharts as ayra, liveChartsUpdated as ayraAt } from "./liveCharts.ayra-starr";
import { liveCharts as asake, liveChartsUpdated as asakeAt } from "./liveCharts.asake";
import { liveCharts as omahLay, liveChartsUpdated as omahLayAt } from "./liveCharts.omah-lay";
import { liveCharts as seyiVibez, liveChartsUpdated as seyiVibezAt } from "./liveCharts.seyi-vibez";
import { liveCharts as victony, liveChartsUpdated as victonyAt } from "./liveCharts.victony";
import { liveCharts as fireboyDml, liveChartsUpdated as fireboyDmlAt } from "./liveCharts.fireboy-dml";

export interface LiveBoard {
  slug: string;
  releases: LiveRelease[];
  updated: string;
  /** Where the page's country panels fetch the full snapshot from. */
  api: string;
  placements: number;
  countries: number;
  numberOnes: number;
  platformTotals: { platform: string; placements: number; numberOnes: number }[];
}

/** Totals derived from the rows, so they can never disagree with what renders. */
function board(slug: string, releases: LiveRelease[], updated: string): LiveBoard {
  const entries = releases.flatMap((r) => r.platforms.flatMap((p) => p.entries));
  const platforms = [...new Set(releases.flatMap((r) => r.platforms.map((p) => p.platform)))];
  return {
    slug,
    releases,
    updated,
    api: `/api/v1/live-charts/${slug}`,
    placements: entries.length,
    countries: countriesOf(entries),
    numberOnes: releases.reduce((n, r) => n + r.platforms.reduce((m, p) => m + p.numberOnes, 0), 0),
    platformTotals: platforms
      .map((platform) => {
        const blocks = releases.flatMap((r) => r.platforms.filter((p) => p.platform === platform));
        return {
          platform,
          placements: blocks.reduce((n, p) => n + p.entries.length, 0),
          numberOnes: blocks.reduce((n, p) => n + p.numberOnes, 0),
        };
      })
      .sort((a, b) => b.placements - a.placements),
  };
}

// Ordered as the board orders itself — most-certified first, then the three
// whose register sweeps are still scheduled. A live board needs no sweep: the
// platform charts are readable today, which is why all nine have one.
export const LIVE_BOARDS: LiveBoard[] = [
  board("wizkid", wizkid, wizkidAt),
  board("davido", davido, davidoAt),
  board("rema", rema, remaAt),
  board("tems", tems, temsAt),
  board("tyla", tyla, tylaAt),
  board("ayra-starr", ayra, ayraAt),
  board("asake", asake, asakeAt),
  board("omah-lay", omahLay, omahLayAt),
  board("seyi-vibez", seyiVibez, seyiVibezAt),
  board("victony", victony, victonyAt),
  board("fireboy-dml", fireboyDml, fireboyDmlAt),
];

export const liveBoardFor = (slug: string) => LIVE_BOARDS.find((b) => b.slug === slug);
export const hasLiveBoard = (slug: string) => LIVE_BOARDS.some((b) => b.slug === slug);
